# Generated by Django 4.2.18 on 2025-02-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='looses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
    ]
