# Generated by Django 4.2.18 on 2025-01-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is42avatarused',
            field=models.BooleanField(default=False),
        ),
    ]
