# Generated by Django 4.2.18 on 2025-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game_mode',
            field=models.CharField(default='classic', max_length=32),
        ),
    ]
