# Generated by Django 4.2.16 on 2025-01-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar42',
            field=models.CharField(null=True),
        ),
    ]
