# Generated by Django 4.2.16 on 2024-12-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dark_theme',
            field=models.BooleanField(default=False),
        ),
    ]
