# Generated by Django 5.1.4 on 2024-12-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='winrate',
            field=models.IntegerField(default=1000),
        ),
    ]
