# Generated by Django 4.2.18 on 2025-02-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='elo_change',
            field=models.IntegerField(default=0),
        ),
    ]
