# Generated by Django 4.2.18 on 2025-01-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycode',
            name='recovery_code',
            field=models.CharField(max_length=16),
        ),
    ]
