# Generated by Django 4.2.18 on 2025-02-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_achievement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
