# Generated by Django 4.2.18 on 2025-02-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gamehistory_game_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='display',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_connected',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='theme',
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
