# Generated by Django 4.2.18 on 2025-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_achievement_userachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='quality',
            field=models.IntegerField(default=2),
        ),
    ]
