# Generated by Django 4.2.18 on 2025-01-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_is_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='quality',
            field=models.IntegerField(default=1),
        ),
    ]
