# Generated by Django 4.2.16 on 2024-12-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_dark_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dark_theme',
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(default='light', max_length=5),
        ),
    ]
