# Generated by Django 4.2.16 on 2025-01-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_avatar'),
        ('api', '0003_remove_customuser_dark_theme_customuser_theme'),
    ]

    operations = [
    ]
