# Generated by Django 4.2.16 on 2024-12-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customuser_winrate_customuser_looses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.IntegerField(default=9999),
        ),
    ]
