# Generated by Django 4.2.16 on 2024-12-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='looses',
            new_name='loss',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='wins',
            new_name='win',
        ),
    ]
