# Generated by Django 4.2.16 on 2025-01-08 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='invite_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
