# Generated by Django 4.2.16 on 2025-01-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
