# Generated by Django 4.2.16 on 2024-12-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_looses_customuser_loss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='test',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tourn_joined',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tourn_win',
            field=models.IntegerField(default=0),
        ),
    ]
