# Generated by Django 4.2.16 on 2024-12-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customuser_test_customuser_tourn_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oauthlog',
            field=models.BooleanField(default=False),
        ),
    ]
