# Generated by Django 4.2.16 on 2025-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gamehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='game_state',
            field=models.CharField(default='waiting', max_length=32),
        ),
    ]
