# Generated by Django 4.2.16 on 2025-01-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_gamehistory_is_finished_customuser_is_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_game_id',
            field=models.IntegerField(default=-1),
        ),
    ]
