# Generated by Django 4.2.16 on 2025-01-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customuser_current_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='tournament_count',
            field=models.IntegerField(default=0),
        ),
    ]
