# Generated by Django 4.2.16 on 2025-01-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_gamehistory_tournament_round2_game_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='tournament_count',
        ),
        migrations.RemoveField(
            model_name='gamehistory',
            name='tournament_round2_game_id',
        ),
        migrations.RemoveField(
            model_name='gamehistory',
            name='tournament_round2_place',
        ),
    ]
