services:
    postgres:
        image: postgres:16.6-alpine3.19
        container_name: postgres
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
        env_file: .env
        secrets:
            - postgres-passwd
        volumes:
            - postgres_data:/var/lib/postgresql/data
        expose:
            - 5432
        networks:
            - transcendence
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h localhost -p $POSTGRES_PORT -U postgres || exit 1"]
            interval: 5s
            timeout: 2s
            retries: 3
    django:
        build: ./django
        image: django
        container_name: django
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
            DJANGO_SUPERUSER_PASSWORD_FILE: /run/secrets/django-passwd
        env_file: .env
        secrets:
            - postgres-passwd
            - django-passwd
        volumes:
            - django_data:/usr/src/app
            - static_data:/usr/src/app/staticfiles
        networks:
            - transcendence
        restart: unless-stopped
    nginx:
        build: ./nginx
        image: nginx
        container_name: nginx
        depends_on:
            django:
                condition: service_started
        expose:
            - 8081
        ports:
            - 8081:8081
        volumes:
            - static_data:/var/www/html
        networks:
            - transcendence
        restart: unless-stopped

networks:
    transcendence:
        name: transcendence

volumes:
    postgres_data:
        name: postgres_data
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/postgres
    django_data:
        name: django_data
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/django
    static_data:
        name: static_data

secrets:
    postgres-passwd:
        file: ./secrets/postgres-passwd.txt
    django-passwd:
        file: ./secrets/django-passwd.txt
