services:
    postgres:
        build: ./postgres
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
        env_file: .env
        secrets:
            - postgres-passwd
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - postgres_logs:/var/log/postgres
        expose:
            - 5432
        networks:
            - transcendence
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h localhost -p $POSTGRES_PORT -U postgres"]
            interval: 5s
            timeout: 2s
            retries: 3
    django:
        build: ./django
        image: django
        container_name: django
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
            DJANGO_SUPERUSER_PASSWORD_FILE: /run/secrets/django-passwd
        env_file: .env
        secrets:
            - postgres-passwd
            - django-passwd
        volumes:
            - django_data:/usr/src/app
            - static_data:/usr/src/app/staticfiles
        expose:
            - 8080
        networks:
            - transcendence
        restart: unless-stopped
    nginx:
        build: ./nginx
        image: nginx
        container_name: nginx
        depends_on:
            django:
                condition: service_started
        expose:
            - 8081
        ports:
            - 8081:8081
        volumes:
            - static_data:/var/www/html
            - nginx_logs:/var/log/nginx
        networks:
            - transcendence
        restart: unless-stopped 
    logstash:
        image: logstash:8.15.5
        container_name: logstash
        depends_on:
            postgres:
                condition: service_healthy
            django:
                condition: service_started
            nginx:
                condition: service_started
        volumes:
            - postgres_logs:/var/log/postgres
            - nginx_logs:/var/log/nginx
        networks:
            - transcendence
        restart: unless-stopped

networks:
    transcendence:
        name: transcendence

volumes:
    postgres_data:
        name: postgres_data
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/postgres
    django_data:
        name: django_data
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/django
    static_data:
        name: static_data
    postgres_logs:
        name: postgres_logs
    nginx_logs:
        name: nginx_logs

secrets:
    postgres-passwd:
        file: ./secrets/postgres-passwd.txt
    django-passwd:
        file: ./secrets/django-passwd.txt
