services:
    postgres:
        build: ${PWD}/docker/postgres
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
        env_file: .env
        secrets:
            - postgres-passwd
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - postgres_logs:/var/log/postgres
        expose:
            - 5432
        networks:
            - transcendence
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -h localhost -p $POSTGRES_PORT -U postgres",
                ]
            interval: 5s
            timeout: 2s
            retries: 3
    django:
        build: ${PWD}/docker/django
        image: django
        container_name: django
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
            JWT_SECRET_KEY_FILE: /run/secrets/jwt-secret-key
            OAUTH_CLIENT_ID_FILE: /run/secrets/oauth-client-id
            OAUTH_CLIENT_SECRET_FILE: /run/secrets/oauth-client-secret
        env_file: .env
        secrets:
            - postgres-passwd
            - jwt-secret-key
            - oauth-client-id
            - oauth-client-secret
        volumes:
            - django_data:/usr/src/app
        networks:
            - transcendence
        restart: unless-stopped
    django_ws:
        build: ${PWD}/docker/django
        image: django
        container_name: django_ws
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
            JWT_SECRET_KEY_FILE: /run/secrets/jwt-secret-key
            DEEPSEEKAPI: /run/secrets/deepseekapi
            OAUTH_CLIENT_ID_FILE: /run/secrets/oauth-client-id
            OAUTH_CLIENT_SECRET_FILE: /run/secrets/oauth-client-secret
        env_file: .env
        secrets:
            - postgres-passwd
            - jwt-secret-key
            - deepseekapi
            - oauth-client-id
            - oauth-client-secret
        volumes:
            - django_data:/usr/src/app
        networks:
            - transcendence
        restart: unless-stopped
    nginx:
        build: ${PWD}/docker/nginx
        image: nginx
        container_name: nginx
        depends_on:
            django:
                condition: service_started
        environment:
            JWT_SECRET_KEY_FILE: /run/secrets/jwt-secret-key
        secrets:
            - jwt-secret-key
        expose:
            - 9000
        ports:
            - "9000:9000"
        volumes:
            - nginx_data:/var/www/html
            - nginx_logs:/var/log/nginx
            - django_data:/var/www/django/media
        networks:
            - transcendence
        restart: unless-stopped
    redis:
        build: ${PWD}/docker/redis
        image: redis
        container_name: redis
        expose:
            - 6379
        networks:
            - transcendence
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 3
    cadvisor:
        build: ${PWD}/docker/cadvisor
        image: cadvisor
        container_name: cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        expose:
            - 8080
        networks:
            - transcendence
        restart: unless-stopped
    node-exporter:
        build: ${PWD}/docker/node-exporter
        image: node-exporter
        container_name: node-exporter
        volumes:
            - /:/rootfs:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
        expose:
            - 9100
        networks:
            - transcendence
        restart: unless-stopped
    prometheus:
        build: ${PWD}/docker/prometheus
        image: prometheus
        container_name: prometheus
        depends_on:
            cadvisor:
                condition: service_started
        environment:
            PROMETHEUS_PASSWORD_FILE: /run/secrets/prometheus-passwd
        env_file: .env
        secrets:
            - prometheus-passwd
        volumes:
            - prometheus_data:/etc/prometheus/data
        expose:
            - 9090
        networks:
            - transcendence
        restart: unless-stopped
    grafana:
        build: ${PWD}/docker/grafana
        image: grafana
        container_name: grafana
        depends_on:
            prometheus:
                condition: service_started
        environment:
            GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana-passwd
            PROMETHEUS_PASSWORD_FILE: /run/secrets/prometheus-passwd
        env_file: .env
        secrets:
            - grafana-passwd
            - prometheus-passwd
        volumes:
            - grafana_data:/var/lib/grafana
        expose:
            - 3000
        networks:
            - transcendence
        restart: unless-stopped

networks:
    transcendence:
        name: transcendence

volumes:
    django_data:
        name: django_data
        driver_opts:
            type: none
            o: bind
            device: ${PWD}/backend
    nginx_data:
        name: nginx_data
        driver_opts:
            type: none
            o: bind
            device: ${PWD}/static
    django_logs:
        name: django_logs
    postgres_data:
        name: postgres_data
    postgres_logs:
        name: postgres_logs
    nginx_logs:
        name: nginx_logs
    elasticsearch_data:
        name: elasticsearch_data
    elasticsearch_logs:
        name: elasticsearch_logs
    kibana_logs:
        name: kibana_logs
    prometheus_data:
        name: prometheus_data
    grafana_data:
        name: grafana_data

secrets:
    postgres-passwd:
        file: ${PWD}/docker/secrets/postgres-passwd.txt
    elasticsearch-passwd:
        file: ${PWD}/docker/secrets/elasticsearch-passwd.txt
    kibana-passwd:
        file: ${PWD}/docker/secrets/kibana-passwd.txt
    prometheus-passwd:
        file: ${PWD}/docker/secrets/prometheus-passwd.txt
    grafana-passwd:
        file: ${PWD}/docker/secrets/grafana-passwd.txt
    jwt-secret-key:
        file: ${PWD}/docker/secrets/jwt-secret-key.txt
    oauth-client-id:
        file: ${PWD}/docker/secrets/oauth-client-id.txt
    oauth-client-secret:
        file: ${PWD}/docker/secrets/oauth-client-secret.txt
    deepseekapi:
        file: ${PWD}/docker/secrets/deepseekapi.txt
